### ISSUE TITLE
ERROR: Referenced sniff "PHPCompatibility.FunctionUse.RemovedFunctions" does not exist

### ISSUE THREAD

**Issue by diazwatson** [codemanufacture/magento-coding-standard-action#9]
![Screenshot 2024-07-17 at 23 17 46](https://github.com/user-attachments/assets/877a18bf-aea5-4586-a60d-064b110e80dd)

Probably related to this: https://magento.stackexchange.com/a/357223/4659

**Comment by piotrkwiecinski** [comment]
@diazwatson could you provide details of your github action. Your log shows `installed_paths` was triggered.

If you could include reproducer it would good.

**Comment by diazwatson** [comment]
Sure

This is the version I initially used (the one that generated the reported error)
```
name: "Magento 2 Coding Standard"
on:
  push:
jobs:
  coding-standard:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0   # Depth is needed for PR violation reports
    - name: Setup PHP with composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        tools: composer:2.3, phpcs:3.6
    - name: Run coding standard analysis
      uses: codemanufacture/magento-coding-standard-action@v1
```


This is the version I am currently using: It is somehow working as I can see the warnings and errors but for some reason it scans the whole source code rather than only the files files changed. 
```
name: "Magento 2 Coding Standard"
on:
  push:
jobs:
  coding-standard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0   # Depth is needed for PR violation reports
      - name: Setup PHP with composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:2.3, phpcs:3.6
      - name: Install PHPCompatibility
        run: composer global require phpcompatibility/php-compatibility
      - name: Set PHPCompatibility path
        run: phpcs --config-set installed_paths ~/.composer/vendor/phpcompatibility/php-compatibility
      - name: Run coding standard analysis
        uses: codemanufacture/magento-coding-standard-action@v1
        with:
          extensions: "php,phtml"
          file_list: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
```

**Comment by piotrkwiecinski** [comment]
Apparently in newer versions of magento https://github.com/magento/PHPCompatibilityFork is used so the install path is `magento/php-compatibility-fork` instead of `phpcompatibility/php-compatibility`.

I'll check if there is a way to detect it.

**Comment by diazwatson** [comment]
How about using what the Magento repo being tested comes with rather than installing `magento/coding-standards` and `magento/php-compatibility-fork` separately?

For example:

If I add the action to a repo containing Magento 2.2, 2.3 or 2.4, then the action will scan the code using what ever version of `magento/coding-standards` is present in that Magento

**Comment by piotrkwiecinski** [comment]
For newest version of magento/coding-standards (v33) `installed_paths` should be:
```
composer global -- exec phpcs --config-set installed_paths ~/.composer/vendor/magento/magento-coding-standard/,~/.composer/vendor/magento/php-compatibility-fork
```             

v32 works correctly without this fix.

**Comment by piotrkwiecinski** [comment]
If your repo already has coding standards installed via vendor:
you can set:
```
- name: Run coding standard analysis
  uses: codemanufacture/magento-coding-standard-action@v1
  with:
    install_coding_standard: false
```

It would attempt to install a separate global package.
